version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - govuk-pay
  - javascript
  allow:
  - dependency-type: "production"
  ignore:
  - dependency-name: aws-sdk
    versions:
    - ">= 2.861.a"
    - "< 2.862"
  - dependency-name: stripe
    versions:
    - "> 7.15.0"
  - dependency-name: stripe
    versions:
    - ">= 7.3.0.a"
    - "< 7.3.1"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - javascript
  ignore:
  - dependency-name: node
    versions:
    - ">= 14.a"
    - "< 15"
  - dependency-name: node
    versions:
    - ">= 15.a"
    - "< 16"
